# Set a plain language title for the site.
title: USWDS Theme Toolkit

# Write a short description for the site. This is used for "meta description."
description: An experiment with documenting UI themes for USWDS sites

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]

# Enable for live hosting on GitHub Pages
baseurl: /ui-doc-demo

# Remove generation of additional style.css
theme: null